---
- hosts: localhost
  connection: local
  
  vars:
    docker_ip: 192.168.59.103
    docker_net: 192.168.59

  tasks:
    - debug :
        var: docker_net

    - fail:
        msg: stop

    - name: install homebrew cask addon
      homebrew:
        name: brew-cask

    - name: Install virtualbox
      homebrew_cask: 
        name: virtualbox

    - name: Install docker
      homebrew: 
        name: docker

    - name: Install vagrant
      homebrew_cask:
        name: vagrant
      register: vagrant_installed

    - name: Setup nfs on current host
      sudo: yes
      sudo_user: root
      lineinfile:
        dest: /etc/exports
        line: /Users -maproot=root -network {{ docker_net }} -mask 255.255.255.0
        create: yes
      register: exports_updated

    - name: Restart NFSD
      sudo: yes
      sudo_user: root
      command: nfsd restart
      when: exports_updated|changed

    - name: Start Vagrant VM
      command: vagrant up

    - name: Get VBox Host IP
      command: 

    - name: Setup docker environment
      lineinfile:
        dest: ~/.profile
        line: export DOCKER_HOST=tcp://{{ docker_ip }}:2375
        create: yes

    - name: Setup docker environment
      lineinfile:
        dest: ~/.bash_profile
        line: export DOCKER_HOST=tcp://{{ docker_ip }}:2375
        create: yes

    - debug:
        msg: "Restart your shell or run - export DOCKER_HOST=tcp://{{ docker_ip }}:2375"
    
